// This file was generated by the Sentry wizard because we couldn't find a root layout file.
import { ClerkProvider } from '@clerk/nextjs';
import * as Sentry from '@sentry/nextjs';
import type { Metadata } from 'next';

export function generateMetadata(): Metadata {
  return {
    other: {
      ...Sentry.getTraceData(),
    },
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>{children}</ClerkProvider>
      </body>
    </html>
  );
}

// Force Node.js runtime to avoid Edge Runtime issues
export const runtime = 'nodejs';
