// Major US cities for autocomplete
export const cities = [
  'New York, NY',
  'Los Angeles, CA',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'San Jose, CA',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'San Francisco, CA',
  'Indianapolis, IN',
  'Seattle, WA',
  'Denver, CO',
  'Washington, DC',
  'Boston, MA',
  'El Paso, TX',
  'Nashville, TN',
  'Detroit, MI',
  'Oklahoma City, OK',
  'Portland, OR',
  'Las Vegas, NV',
  'Memphis, TN',
  'Louisville, KY',
  'Baltimore, MD',
  'Milwaukee, WI',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Sacramento, CA',
  'Mesa, AZ',
  'Kansas City, MO',
  'Atlanta, GA',
  'Long Beach, CA',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Miami, FL',
  'Virginia Beach, VA',
  'Omaha, NE',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tulsa, OK',
  'Tampa, FL',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Corpus Christi, TX',
  'Riverside, CA',
  'Lexington, KY',
  'Stockton, CA',
  'Henderson, NV',
  'Saint Paul, MN',
  'St. Louis, MO',
  'Fort Wayne, IN',
  'Jersey City, NJ',
  'Chandler, AZ',
  'Madison, WI',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Buffalo, NY',
  'Gilbert, AZ',
  'Glendale, AZ',
  'North Las Vegas, NV',
  'Winston-Salem, NC',
  'Chesapeake, VA',
  'Norfolk, VA',
  'Fremont, CA',
  'Garland, TX',
  'Irving, TX',
  'Hialeah, FL',
  'Richmond, VA',
  'Boise, ID',
  'Spokane, WA',
  'Baton Rouge, LA',
  'Tacoma, WA',
  'San Bernardino, CA',
  'Grand Rapids, MI',
  'Huntsville, AL',
  'Salt Lake City, UT',
  'Frisco, TX',
  'Yonkers, NY',
  'Amarillo, TX',
  'Glendale, CA',
  'McKinney, TX',
  'Montgomery, AL',
  'Aurora, IL',
  'Des Moines, IA',
  'Modesto, CA',
  'Fayetteville, NC',
  'Shreveport, LA',
  'Tacoma, WA',
  'Oxnard, CA',
  'Fontana, CA',
  'Columbus, GA',
  'Montgomery, AL',
  'Moreno Valley, CA',
  'Huntington Beach, CA',
  'Yonkers, NY',
  'Amarillo, TX',
  'Glendale, CA',
  'McKinney, TX',
  'Montgomery, AL',
  'Aurora, IL',
  'Des Moines, IA',
  'Modesto, CA',
  'Fayetteville, NC',
  'Shreveport, LA',
];
